### ISSUE TITLE
Make `void` a generic BindingIdentifier

### ISSUE THREAD

**Issue by bergus** [tc39/proposal-explicit-resource-management#88] opened 2022-05-27 00:13 UTC
The proposal currently only allows `using void = …` as a special form of the *[UsingDeclaration](https://tc39.es/proposal-explicit-resource-management/#prod-UsingDeclaration)*, adding a special case *[+Using] `void` [Initializer](https://tc39.es/ecma262/#prod-Initializer)* to the *[LexicalBinding](https://tc39.es/proposal-explicit-resource-management/#prod-LexicalBinding)* production.

I think it would be more consistent to allow `void` in any place where a *[BindingIdentifier](https://tc39.es/ecma262/#prod-BindingIdentifier)* is allowed. This would allow a lot of useful patterns where currently `_` is often used to indicate an unused variable (or `_unused1`, `_unused2` if multiple bindings were to be declared):
```js
const void = …;
let void = …;
var void = …;
using void = …;
for (const void of …) {…}
const {x: void, y: void, ...rest} = …;
const [void, void, ...rest] = …;
function …(void, second) {…}
onClick = (void) => {…};

**Comment by rbuckton** [comment] 2022-05-27 04:05
This is a duplicate of #77, and I've already commented as to my position in that issue.

**Closed by rbuckton** 2022-05-27 04:05 UTC
Labels: duplicate
